spring:
  application:
    name: spring-react-ui
  profiles:
    active: dev,local
  config:
    import: optional:configserver:http://localhost:8888
  thymeleaf:
    prefix: classpath:/static/

server:
  port: 8080 #port where discovery client is registered, don't change this port react fetch operations hard coded with this port

management:
  endpoints:
    web:
      exposure:
        include=metrics,info,mappings: